trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Usar .NET SDK 9.x'
  inputs:
    packageType: 'sdk'
    version: '9.x'

- task: DotNetCoreCLI@2
  displayName: 'Publish Vinto.Api'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Vinto.Api.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy a App Service Linux'
  inputs:
    azureSubscription: 'Azure-Vinto'
    appType: 'webAppLinux'
    appName: 'vinto-carripollo-api-dev-linux'
    package: '$(Build.ArtifactStagingDirectory)/publish/*.zip'
    runtimeStack: 'DOTNETCORE|9.0'
    startUpCommand: 'dotnet Vinto.Api.dll'